spring.application.name=CadastroDeNinjas
spring.datasource.url=jdbc:h2:file:./data/CadastroDeNinjasDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=cadastro_bd
spring.datasource.password=cadastro_bd

# aq sao as settings do JPA // hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
